# Generated by Django 4.0.5 on 2022-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_rename_is_admin_user_is_profile_neighbourhood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_profile',
            field=models.BooleanField(default=False, verbose_name='Is profile'),
        ),
    ]
