# Generated by Django 4.0.5 on 2022-06-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_user_is_admin_alter_user_is_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='user',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighbourhood', to='hood.admin'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='hood.profile'),
        ),
    ]
