# Generated by Django 4.0.5 on 2022-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_alter_admin_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
