# Generated by Django 4.0.5 on 2022-06-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='admin',
        ),
    ]
